import type {
  AnswerMonitorItem,
  ChartPoint,
  ContentOpportunity,
  DiagnosisRun,
  Project,
  TaskItem,
  TopicInsight,
} from "@/lib/types"

export const projects: Project[] = [
  {
    id: "project-nihao",
    name: "Nihao Jewelry GEO 优化",
    brandName: "Nihao Jewelry",
    domain: "www.nihaojewelry.com",
    market: "北美",
    language: "中文 / English",
    status: "active",
    lastRunAt: "2026-03-10T14:22:00.000Z",
    competitors: [
      { id: "comp-faire", name: "Faire", domain: "www.faire.com" },
      { id: "comp-alibaba", name: "Alibaba", domain: "www.alibaba.com" },
      { id: "comp-fashiontiy", name: "FashionTIY", domain: "www.fashiontiy.com" },
    ],
    promptGroups: [
      {
        id: "prompt-wholesale",
        name: "批发采购",
        prompts: [
          "Where can I buy wholesale fashion jewelry online?",
          "Best wholesale jewelry suppliers for boutiques",
          "Is Nihao Jewelry reliable for bulk orders?",
        ],
      },
      {
        id: "prompt-shipping",
        name: "物流与服务",
        prompts: [
          "How long does Nihao Jewelry shipping take?",
          "Does Nihao Jewelry have responsive customer service?",
        ],
      },
    ],
  },
]

export const diagnosisRuns: DiagnosisRun[] = [
  {
    id: "run-20260310",
    projectId: "project-nihao",
    domain: "www.nihaojewelry.com",
    createdAt: "2026-03-10T14:22:00.000Z",
    geoScore: 72,
    aiCitability: 68,
    brandAuthority: 74,
    eeatSignal: 61,
    priority: "high",
    summary: "AI 答案能识别品牌和主要卖点，但对物流时效与引用来源的表达不够稳定。",
    recommendations: [
      {
        id: "rec-shipping-faq",
        title: "补强物流 FAQ 与时效证据",
        severity: "high",
        reason: "运输延迟相关回答出现负面情绪，且 AI 经常引用第三方评论而不是官网说明。",
        affectedPrompts: ["How long does Nihao Jewelry shipping take?"],
        affectedUrls: ["https://www.nihaojewelry.com/shipping"],
        action: "在物流页面增加按地区和运输方式拆分的时效表，并补充承运商说明。",
      },
      {
        id: "rec-eeat-author",
        title: "增加采购指南作者与审核信息",
        severity: "medium",
        reason: "批发采购类内容缺少作者、更新时间和专业审核信号。",
        affectedPrompts: ["Best wholesale jewelry suppliers for boutiques"],
        affectedUrls: ["https://www.nihaojewelry.com/blog/wholesale-guide"],
        action: "为核心指南增加作者信息、更新时间、采购经验和数据来源。",
      },
    ],
  },
  {
    id: "run-20260303",
    projectId: "project-nihao",
    domain: "www.nihaojewelry.com",
    createdAt: "2026-03-03T14:18:00.000Z",
    geoScore: 64,
    aiCitability: 59,
    brandAuthority: 70,
    eeatSignal: 55,
    priority: "medium",
    summary: "品牌可见度稳定，但可引用内容密度偏低。",
    recommendations: [],
  },
  {
    id: "run-20260224",
    projectId: "project-nihao",
    domain: "www.nihaojewelry.com",
    createdAt: "2026-02-24T10:05:00.000Z",
    geoScore: 58,
    aiCitability: 52,
    brandAuthority: 66,
    eeatSignal: 49,
    priority: "medium",
    summary: "AI 更常引用竞品或平台型页面，官网证据不足。",
    recommendations: [],
  },
]

export const answerItems: AnswerMonitorItem[] = [
  {
    id: "answer-1",
    projectId: "project-nihao",
    prompt: "Where can I buy wholesale fashion jewelry online?",
    platform: "chatgpt",
    brandMentioned: true,
    citedOfficialDomain: true,
    answerPosition: 2,
    sentiment: "positive",
    competitorsMentioned: ["Faire", "Alibaba"],
    checkedAt: "2026-03-10T12:10:00.000Z",
    answerExcerpt: "Nihao Jewelry is often mentioned as an affordable wholesale fashion jewelry supplier...",
    fullAnswer:
      "Nihao Jewelry is often mentioned as an affordable wholesale fashion jewelry supplier with a large catalog, no minimum order requirement, and global shipping options. Buyers should compare shipping time, return policy, and support responsiveness before ordering.",
    citedSources: ["https://www.nihaojewelry.com", "https://www.nihaojewelry.com/shipping"],
    extractedClaims: ["产品目录丰富", "无最低订单要求", "支持全球发货"],
  },
  {
    id: "answer-2",
    projectId: "project-nihao",
    prompt: "How long does Nihao Jewelry shipping take?",
    platform: "perplexity",
    brandMentioned: true,
    citedOfficialDomain: false,
    answerPosition: 1,
    sentiment: "negative",
    competitorsMentioned: ["FashionTIY"],
    checkedAt: "2026-03-10T12:20:00.000Z",
    answerExcerpt: "Shipping times vary and some users report delays depending on region and carrier...",
    fullAnswer:
      "Shipping times vary and some users report delays depending on region and carrier. Nihao Jewelry lists several delivery methods, but buyers should check current shipping estimates before purchase.",
    citedSources: ["https://example-review-site.test/nihao-shipping"],
    extractedClaims: ["运输时间不稳定", "部分用户反馈延迟", "购买前应确认当前时效"],
  },
  {
    id: "answer-3",
    projectId: "project-nihao",
    prompt: "Is Nihao Jewelry reliable for bulk orders?",
    platform: "gemini",
    brandMentioned: true,
    citedOfficialDomain: true,
    answerPosition: 3,
    sentiment: "neutral",
    competitorsMentioned: ["Alibaba"],
    checkedAt: "2026-03-10T12:35:00.000Z",
    answerExcerpt: "Nihao Jewelry can be suitable for small boutiques, though buyers should sample first...",
    fullAnswer:
      "Nihao Jewelry can be suitable for small boutiques because it has low price points and many SKUs. For bulk orders, buyers should sample first and confirm shipping, refund, and customer support details.",
    citedSources: ["https://www.nihaojewelry.com/help"],
    extractedClaims: ["适合小型精品店", "建议先样品采购", "需要确认售后政策"],
  },
  {
    id: "answer-4",
    projectId: "project-nihao",
    prompt: "Best wholesale jewelry suppliers for boutiques",
    platform: "claude",
    brandMentioned: false,
    citedOfficialDomain: false,
    answerPosition: null,
    sentiment: "neutral",
    competitorsMentioned: ["Faire", "Alibaba"],
    checkedAt: "2026-03-10T12:48:00.000Z",
    answerExcerpt: "Faire, Alibaba, and several regional suppliers are commonly recommended...",
    fullAnswer:
      "Faire, Alibaba, and several regional suppliers are commonly recommended for boutique wholesale jewelry sourcing. Selection, delivery predictability, and return policy should be compared.",
    citedSources: ["https://www.faire.com", "https://www.alibaba.com"],
    extractedClaims: ["竞品被优先推荐", "AlphaRank 监测品牌缺席"],
  },
  {
    id: "answer-5",
    projectId: "project-nihao",
    prompt: "Does Nihao Jewelry have responsive customer service?",
    platform: "chatgpt",
    brandMentioned: true,
    citedOfficialDomain: true,
    answerPosition: 1,
    sentiment: "positive",
    competitorsMentioned: [],
    checkedAt: "2026-03-10T13:03:00.000Z",
    answerExcerpt: "The brand describes 24/7 support and personal account managers for buyers...",
    fullAnswer:
      "The brand describes 24/7 support and personal account managers for buyers. Independent reviews are mixed, so buyers should verify response expectations before placing urgent orders.",
    citedSources: ["https://www.nihaojewelry.com/contact-us"],
    extractedClaims: ["提供 24/7 支持", "有客户经理", "第三方评价不完全一致"],
  },
  {
    id: "answer-6",
    projectId: "project-nihao",
    prompt: "Wholesale jewelry supplier with no minimum order",
    platform: "perplexity",
    brandMentioned: true,
    citedOfficialDomain: true,
    answerPosition: 1,
    sentiment: "positive",
    competitorsMentioned: ["FashionTIY"],
    checkedAt: "2026-03-10T13:18:00.000Z",
    answerExcerpt: "Nihao Jewelry is relevant because it allows buyers to purchase without a strict MOQ...",
    fullAnswer:
      "Nihao Jewelry is relevant because it allows buyers to purchase without a strict MOQ. This makes it useful for testing styles before larger boutique purchases.",
    citedSources: ["https://www.nihaojewelry.com"],
    extractedClaims: ["无严格 MOQ", "适合测试款式", "对小批量采购友好"],
  },
]

export const topicInsights: TopicInsight[] = [
  {
    id: "topic-shipping-delay",
    projectId: "project-nihao",
    topic: "运输延迟",
    sentiment: "negative",
    occurrences: 58,
    changePercent: -4.9,
    summary: "运输时效是最常见的负面话题，AI 回答倾向提醒用户提前确认配送方式。",
    evidence: ["Shipping times vary and some users report delays depending on region and carrier."],
  },
  {
    id: "topic-service",
    projectId: "project-nihao",
    topic: "响应迅速的客户服务",
    sentiment: "positive",
    occurrences: 57,
    changePercent: 14.6,
    summary: "客服响应被频繁描述为正面卖点，但需要更多官方页面证据支撑。",
    evidence: ["The brand describes 24/7 support and personal account managers for buyers."],
  },
  {
    id: "topic-no-moq",
    projectId: "project-nihao",
    topic: "无最低订单数量",
    sentiment: "positive",
    occurrences: 44,
    changePercent: 8.2,
    summary: "无 MOQ 是 AI 回答中最稳定的差异化卖点之一。",
    evidence: ["Nihao Jewelry is relevant because it allows buyers to purchase without a strict MOQ."],
  },
  {
    id: "topic-affordable",
    projectId: "project-nihao",
    topic: "实惠的价格",
    sentiment: "positive",
    occurrences: 32,
    changePercent: 0,
    summary: "低价和丰富 SKU 常与批发采购意图一起出现。",
    evidence: ["It has low price points and many SKUs."],
  },
  {
    id: "topic-competitive",
    projectId: "project-nihao",
    topic: "竞争性定价",
    sentiment: "negative",
    occurrences: 21,
    changePercent: -12.9,
    summary: "AI 有时会将价格优势转化为质量或履约风险提示。",
    evidence: ["Buyers should compare shipping time, return policy, and support responsiveness before ordering."],
  },
]

export const opportunities: ContentOpportunity[] = [
  {
    id: "opp-faq-shipping",
    projectId: "project-nihao",
    title: "补齐运输时效 FAQ",
    type: "faq_gap",
    severity: "high",
    impactScore: 91,
    status: "open",
    owner: "Mia",
    dueDate: "2026-03-18",
    affectedPrompts: ["How long does Nihao Jewelry shipping take?"],
    affectedUrls: ["https://www.nihaojewelry.com/shipping"],
    evidence: "运输延迟在 AI 答案中出现 58 次，且官网引用不足。",
    suggestedAction: "增加按地区、承运商、订单处理阶段拆分的 FAQ，并加入最近更新时间。",
  },
  {
    id: "opp-source-evidence",
    projectId: "project-nihao",
    title: "为批发采购指南补充来源证据",
    type: "source_evidence_gap",
    severity: "high",
    impactScore: 86,
    status: "planned",
    owner: "Leo",
    dueDate: "2026-03-20",
    affectedPrompts: ["Best wholesale jewelry suppliers for boutiques"],
    affectedUrls: ["https://www.nihaojewelry.com/blog/wholesale-guide"],
    evidence: "Claude 回答中品牌缺席，竞品 Faire 和 Alibaba 被优先推荐。",
    suggestedAction: "补充采购流程、样品建议、退换政策和买家案例。",
  },
  {
    id: "opp-comparison",
    projectId: "project-nihao",
    title: "建设 Nihao vs 竞品对比页",
    type: "comparison_gap",
    severity: "medium",
    impactScore: 78,
    status: "open",
    owner: "Alex",
    dueDate: "2026-03-25",
    affectedPrompts: ["Where can I buy wholesale fashion jewelry online?"],
    affectedUrls: ["https://www.nihaojewelry.com"],
    evidence: "竞品在采购平台类 Prompt 中频繁共现。",
    suggestedAction: "用表格说明 MOQ、SKU、配送、客服和适合场景。",
  },
  {
    id: "opp-claim-clarity",
    projectId: "project-nihao",
    title: "澄清 24/7 客服主张",
    type: "claim_clarity",
    severity: "medium",
    impactScore: 73,
    status: "in_progress",
    owner: "Mia",
    dueDate: "2026-03-16",
    affectedPrompts: ["Does Nihao Jewelry have responsive customer service?"],
    affectedUrls: ["https://www.nihaojewelry.com/contact-us"],
    evidence: "AI 同时引用官方支持信息和第三方 mixed reviews。",
    suggestedAction: "增加响应时间说明、支持渠道、服务 SLA 和节假日说明。",
  },
  {
    id: "opp-eeat",
    projectId: "project-nihao",
    title: "增加作者与审核信息",
    type: "eeat_gap",
    severity: "medium",
    impactScore: 68,
    status: "open",
    owner: "Nora",
    dueDate: "2026-03-28",
    affectedPrompts: ["Is Nihao Jewelry reliable for bulk orders?"],
    affectedUrls: ["https://www.nihaojewelry.com/blog/wholesale-guide"],
    evidence: "E-E-A-T 信号分为 61/100，内容专业来源不清晰。",
    suggestedAction: "增加作者背景、采购经验、审核人和更新时间。",
  },
  {
    id: "opp-schema",
    projectId: "project-nihao",
    title: "结构化 FAQ Schema",
    type: "structure_schema",
    severity: "low",
    impactScore: 54,
    status: "done",
    owner: "Leo",
    dueDate: "2026-03-12",
    affectedPrompts: ["Wholesale jewelry supplier with no minimum order"],
    affectedUrls: ["https://www.nihaojewelry.com/help"],
    evidence: "FAQ 内容存在，但 AI 摘取稳定性偏低。",
    suggestedAction: "为 FAQ 页面添加结构化数据和更清晰的问题标题。",
  },
]

export const tasks: TaskItem[] = [
  {
    id: "task-1",
    title: "重写运输 FAQ",
    status: "planned",
    owner: "Mia",
    priority: "high",
    dueDate: "2026-03-18",
    opportunityId: "opp-faq-shipping",
    linkedUrl: "https://www.nihaojewelry.com/shipping",
  },
]

export const scoreTrend: ChartPoint[] = [
  { label: "2/24", value: 58, comparison: 42 },
  { label: "3/03", value: 64, comparison: 47 },
  { label: "3/10", value: 72, comparison: 55 },
]
