import type {
  AnswerMonitorItem,
  ChartPoint,
  ContentOpportunity,
  DiagnosisRun,
  Project,
  TaskItem,
  TopicInsight,
} from "@/lib/types"

export const projects: Project[] = [
  {
    id: "project-nihao",
    name: "Nihao Jewelry GEO Optimization",
    brandName: "Nihao Jewelry",
    domain: "www.nihaojewelry.com",
    market: "North America",
    language: "Chinese / English",
    status: "active",
    lastRunAt: "2026-03-10T14:22:00.000Z",
    competitors: [
      { id: "comp-faire", name: "Faire", domain: "www.faire.com" },
      { id: "comp-alibaba", name: "Alibaba", domain: "www.alibaba.com" },
      { id: "comp-fashiontiy", name: "FashionTIY", domain: "www.fashiontiy.com" },
    ],
    promptGroups: [
      {
        id: "prompt-wholesale",
        name: "Wholesale Sourcing",
        prompts: [
          "Where can I buy wholesale fashion jewelry online?",
          "Best wholesale jewelry suppliers for boutiques",
          "Is Nihao Jewelry reliable for bulk orders?",
        ],
      },
      {
        id: "prompt-shipping",
        name: "Shipping and Service",
        prompts: [
          "How long does Nihao Jewelry shipping take?",
          "Does Nihao Jewelry have responsive customer service?",
        ],
      },
    ],
  },
]

export const diagnosisRuns: DiagnosisRun[] = [
  {
    id: "run-20260310",
    projectId: "project-nihao",
    domain: "www.nihaojewelry.com",
    createdAt: "2026-03-10T14:22:00.000Z",
    geoScore: 72,
    aiCitability: 68,
    brandAuthority: 74,
    eeatSignal: 61,
    priority: "high",
    summary: "AI answers recognize the brand and its core value props, but shipping timelines and citation sources are still inconsistent.",
    recommendations: [
      {
        id: "rec-shipping-faq",
        title: "Strengthen Shipping FAQ and Delivery Evidence",
        severity: "high",
        reason: "Shipping-delay answers show negative sentiment, and AI often cites third-party reviews instead of official site guidance.",
        affectedPrompts: ["How long does Nihao Jewelry shipping take?"],
        affectedUrls: ["https://www.nihaojewelry.com/shipping"],
        action: "Add delivery-time tables by region and carrier method on the shipping page, with carrier notes.",
      },
      {
        id: "rec-eeat-author",
        title: "Add Author and Review Details to the Sourcing Guide",
        severity: "medium",
        reason: "Wholesale sourcing content lacks author, update, and expert review signals.",
        affectedPrompts: ["Best wholesale jewelry suppliers for boutiques"],
        affectedUrls: ["https://www.nihaojewelry.com/blog/wholesale-guide"],
        action: "Add author details, update dates, sourcing experience, and data sources to core guides.",
      },
    ],
  },
  {
    id: "run-20260303",
    projectId: "project-nihao",
    domain: "www.nihaojewelry.com",
    createdAt: "2026-03-03T14:18:00.000Z",
    geoScore: 64,
    aiCitability: 59,
    brandAuthority: 70,
    eeatSignal: 55,
    priority: "medium",
    summary: "Brand visibility is stable, but citability density remains low.",
    recommendations: [],
  },
  {
    id: "run-20260224",
    projectId: "project-nihao",
    domain: "www.nihaojewelry.com",
    createdAt: "2026-02-24T10:05:00.000Z",
    geoScore: 58,
    aiCitability: 52,
    brandAuthority: 66,
    eeatSignal: 49,
    priority: "medium",
    summary: "AI more often cites competitors or marketplace pages, while official evidence is insufficient.",
    recommendations: [],
  },
]

export const answerItems: AnswerMonitorItem[] = [
  {
    id: "answer-1",
    projectId: "project-nihao",
    prompt: "Where can I buy wholesale fashion jewelry online?",
    platform: "chatgpt",
    brandMentioned: true,
    citedOfficialDomain: true,
    answerPosition: 2,
    sentiment: "positive",
    competitorsMentioned: ["Faire", "Alibaba"],
    checkedAt: "2026-03-10T12:10:00.000Z",
    answerExcerpt: "Nihao Jewelry is often mentioned as an affordable wholesale fashion jewelry supplier...",
    fullAnswer:
      "Nihao Jewelry is often mentioned as an affordable wholesale fashion jewelry supplier with a large catalog, no minimum order requirement, and global shipping options. Buyers should compare shipping time, return policy, and support responsiveness before ordering.",
    citedSources: ["https://www.nihaojewelry.com", "https://www.nihaojewelry.com/shipping"],
    extractedClaims: ["Rich product catalog", "No minimum order requirement", "Supports global shipping"],
  },
  {
    id: "answer-2",
    projectId: "project-nihao",
    prompt: "How long does Nihao Jewelry shipping take?",
    platform: "perplexity",
    brandMentioned: true,
    citedOfficialDomain: false,
    answerPosition: 1,
    sentiment: "negative",
    competitorsMentioned: ["FashionTIY"],
    checkedAt: "2026-03-10T12:20:00.000Z",
    answerExcerpt: "Shipping times vary and some users report delays depending on region and carrier...",
    fullAnswer:
      "Shipping times vary and some users report delays depending on region and carrier. Nihao Jewelry lists several delivery methods, but buyers should check current shipping estimates before purchase.",
    citedSources: ["https://example-review-site.test/nihao-shipping"],
    extractedClaims: ["Shipping times are inconsistent", "Some users report delays", "Confirm current delivery estimates before purchase"],
  },
  {
    id: "answer-3",
    projectId: "project-nihao",
    prompt: "Is Nihao Jewelry reliable for bulk orders?",
    platform: "gemini",
    brandMentioned: true,
    citedOfficialDomain: true,
    answerPosition: 3,
    sentiment: "neutral",
    competitorsMentioned: ["Alibaba"],
    checkedAt: "2026-03-10T12:35:00.000Z",
    answerExcerpt: "Nihao Jewelry can be suitable for small boutiques, though buyers should sample first...",
    fullAnswer:
      "Nihao Jewelry can be suitable for small boutiques because it has low price points and many SKUs. For bulk orders, buyers should sample first and confirm shipping, refund, and customer support details.",
    citedSources: ["https://www.nihaojewelry.com/help"],
    extractedClaims: ["Suitable for small boutiques", "Sample first before bulk ordering", "Confirm after-sales policy"],
  },
  {
    id: "answer-4",
    projectId: "project-nihao",
    prompt: "Best wholesale jewelry suppliers for boutiques",
    platform: "claude",
    brandMentioned: false,
    citedOfficialDomain: false,
    answerPosition: null,
    sentiment: "neutral",
    competitorsMentioned: ["Faire", "Alibaba"],
    checkedAt: "2026-03-10T12:48:00.000Z",
    answerExcerpt: "Faire, Alibaba, and several regional suppliers are commonly recommended...",
    fullAnswer:
      "Faire, Alibaba, and several regional suppliers are commonly recommended for boutique wholesale jewelry sourcing. Selection, delivery predictability, and return policy should be compared.",
    citedSources: ["https://www.faire.com", "https://www.alibaba.com"],
    extractedClaims: ["Competitors are recommended first", "The monitored AlphaRank brand is absent"],
  },
  {
    id: "answer-5",
    projectId: "project-nihao",
    prompt: "Does Nihao Jewelry have responsive customer service?",
    platform: "chatgpt",
    brandMentioned: true,
    citedOfficialDomain: true,
    answerPosition: 1,
    sentiment: "positive",
    competitorsMentioned: [],
    checkedAt: "2026-03-10T13:03:00.000Z",
    answerExcerpt: "The brand describes 24/7 support and personal account managers for buyers...",
    fullAnswer:
      "The brand describes 24/7 support and personal account managers for buyers. Independent reviews are mixed, so buyers should verify response expectations before placing urgent orders.",
    citedSources: ["https://www.nihaojewelry.com/contact-us"],
    extractedClaims: ["Offers 24/7 support", "Has account managers", "Third-party reviews are mixed"],
  },
  {
    id: "answer-6",
    projectId: "project-nihao",
    prompt: "Wholesale jewelry supplier with no minimum order",
    platform: "perplexity",
    brandMentioned: true,
    citedOfficialDomain: true,
    answerPosition: 1,
    sentiment: "positive",
    competitorsMentioned: ["FashionTIY"],
    checkedAt: "2026-03-10T13:18:00.000Z",
    answerExcerpt: "Nihao Jewelry is relevant because it allows buyers to purchase without a strict MOQ...",
    fullAnswer:
      "Nihao Jewelry is relevant because it allows buyers to purchase without a strict MOQ. This makes it useful for testing styles before larger boutique purchases.",
    citedSources: ["https://www.nihaojewelry.com"],
    extractedClaims: ["No strict MOQ", "Good for testing styles", "Friendly for small-batch sourcing"],
  },
]

export const topicInsights: TopicInsight[] = [
  {
    id: "topic-shipping-delay",
    projectId: "project-nihao",
    topic: "Shipping Delays",
    sentiment: "negative",
    occurrences: 58,
    changePercent: -4.9,
    summary: "Delivery timing is the most common negative topic, and AI answers tend to tell users to confirm shipping methods in advance.",
    evidence: ["Shipping times vary and some users report delays depending on region and carrier."],
  },
  {
    id: "topic-service",
    projectId: "project-nihao",
    topic: "Responsive Customer Service",
    sentiment: "positive",
    occurrences: 57,
    changePercent: 14.6,
    summary: "Customer support is frequently described as a positive selling point, but needs more official-page evidence.",
    evidence: ["The brand describes 24/7 support and personal account managers for buyers."],
  },
  {
    id: "topic-no-moq",
    projectId: "project-nihao",
    topic: "No Minimum Order Quantity",
    sentiment: "positive",
    occurrences: 44,
    changePercent: 8.2,
    summary: "No MOQ is one of the most stable differentiators in AI answers.",
    evidence: ["Nihao Jewelry is relevant because it allows buyers to purchase without a strict MOQ."],
  },
  {
    id: "topic-affordable",
    projectId: "project-nihao",
    topic: "Affordable Pricing",
    sentiment: "positive",
    occurrences: 32,
    changePercent: 0,
    summary: "Low prices and broad SKU coverage often appear with wholesale sourcing intent.",
    evidence: ["It has low price points and many SKUs."],
  },
  {
    id: "topic-competitive",
    projectId: "project-nihao",
    topic: "Competitive Pricing",
    sentiment: "negative",
    occurrences: 21,
    changePercent: -12.9,
    summary: "AI sometimes turns pricing advantages into quality or fulfillment risk caveats.",
    evidence: ["Buyers should compare shipping time, return policy, and support responsiveness before ordering."],
  },
]

export const opportunities: ContentOpportunity[] = [
  {
    id: "opp-faq-shipping",
    projectId: "project-nihao",
    title: "Complete the Shipping Timeline FAQ",
    type: "faq_gap",
    severity: "high",
    impactScore: 91,
    status: "open",
    owner: "Mia",
    dueDate: "2026-03-18",
    affectedPrompts: ["How long does Nihao Jewelry shipping take?"],
    affectedUrls: ["https://www.nihaojewelry.com/shipping"],
    evidence: "Shipping delays appeared 58 times in AI answers, with insufficient official citations.",
    suggestedAction: "Add FAQ entries by region, carrier, and order-processing stage, including the latest update time.",
  },
  {
    id: "opp-source-evidence",
    projectId: "project-nihao",
    title: "Add Source Evidence to the Wholesale Sourcing Guide",
    type: "source_evidence_gap",
    severity: "high",
    impactScore: 86,
    status: "planned",
    owner: "Leo",
    dueDate: "2026-03-20",
    affectedPrompts: ["Best wholesale jewelry suppliers for boutiques"],
    affectedUrls: ["https://www.nihaojewelry.com/blog/wholesale-guide"],
    evidence: "The brand is absent in Claude answers, while Faire and Alibaba are recommended first.",
    suggestedAction: "Add sourcing workflow, sample guidance, return policy, and buyer cases.",
  },
  {
    id: "opp-comparison",
    projectId: "project-nihao",
    title: "Build a Nihao vs Competitors Comparison Page",
    type: "comparison_gap",
    severity: "medium",
    impactScore: 78,
    status: "open",
    owner: "Alex",
    dueDate: "2026-03-25",
    affectedPrompts: ["Where can I buy wholesale fashion jewelry online?"],
    affectedUrls: ["https://www.nihaojewelry.com"],
    evidence: "Competitors frequently co-occur in marketplace sourcing prompts.",
    suggestedAction: "Use a table to explain MOQ, SKU coverage, delivery, support, and best-fit scenarios.",
  },
  {
    id: "opp-claim-clarity",
    projectId: "project-nihao",
    title: "Clarify the 24/7 Support Claim",
    type: "claim_clarity",
    severity: "medium",
    impactScore: 73,
    status: "in_progress",
    owner: "Mia",
    dueDate: "2026-03-16",
    affectedPrompts: ["Does Nihao Jewelry have responsive customer service?"],
    affectedUrls: ["https://www.nihaojewelry.com/contact-us"],
    evidence: "AI cites both official support information and third-party mixed reviews.",
    suggestedAction: "Add response-time expectations, support channels, service SLA, and holiday coverage.",
  },
  {
    id: "opp-eeat",
    projectId: "project-nihao",
    title: "Add Author and Review Information",
    type: "eeat_gap",
    severity: "medium",
    impactScore: 68,
    status: "open",
    owner: "Nora",
    dueDate: "2026-03-28",
    affectedPrompts: ["Is Nihao Jewelry reliable for bulk orders?"],
    affectedUrls: ["https://www.nihaojewelry.com/blog/wholesale-guide"],
    evidence: "E-E-A-T signal score is 61/100, and expert sources are unclear.",
    suggestedAction: "Add author background, sourcing experience, reviewer, and updated date.",
  },
  {
    id: "opp-schema",
    projectId: "project-nihao",
    title: "Structure FAQ Schema",
    type: "structure_schema",
    severity: "low",
    impactScore: 54,
    status: "done",
    owner: "Leo",
    dueDate: "2026-03-12",
    affectedPrompts: ["Wholesale jewelry supplier with no minimum order"],
    affectedUrls: ["https://www.nihaojewelry.com/help"],
    evidence: "FAQ content exists, but AI extraction stability is low.",
    suggestedAction: "Add structured data and clearer question titles to FAQ pages.",
  },
]

export const tasks: TaskItem[] = [
  {
    id: "task-1",
    title: "Rewrite Shipping FAQ",
    status: "planned",
    owner: "Mia",
    priority: "high",
    dueDate: "2026-03-18",
    opportunityId: "opp-faq-shipping",
    linkedUrl: "https://www.nihaojewelry.com/shipping",
  },
]

export const scoreTrend: ChartPoint[] = [
  { label: "2/24", value: 58, comparison: 42 },
  { label: "3/03", value: 64, comparison: 47 },
  { label: "3/10", value: 72, comparison: 55 },
]
