import { ArrowUpRight, CalendarDays, MessageCircle, Mountain, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { overviewMetrics, workflowColumns } from "@/data/tourism";

export function OverviewPage({ onMonitor }: { onMonitor: () => void }) {
  return <div className="content-grid">
    <section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><Badge variant="default" className="mb-3">TRAVEL KOS · 旅游增长运营</Badge><h2 className="text-2xl font-bold tracking-tight md:text-3xl">把每一次咨询，变成一段好旅程</h2><p className="mt-2 max-w-2xl text-sm text-muted-foreground">从内容触达到出行服务，统一看见游客状态、渠道质量和下一步动作。</p></div><Button onClick={onMonitor}>进入游客监控<ArrowUpRight className="h-4 w-4" /></Button></section>
    <section className="grid gap-4 md:grid-cols-3">{overviewMetrics.map((metric) => <Card key={metric.label} className="transition-shadow hover:shadow-md"><CardHeader className="flex-row items-center justify-between space-y-0 pb-2"><CardTitle className="text-sm font-medium text-muted-foreground">{metric.label}</CardTitle><span className="rounded-full bg-muted p-2"><CalendarDays className="h-4 w-4 text-primary" /></span></CardHeader><CardContent><div className="flex items-baseline gap-1"><span className="text-3xl font-bold tracking-tight">{metric.value}</span><span className="text-sm text-muted-foreground">{metric.unit}</span></div><p className="mt-2 text-xs text-emerald-600">较昨日 {metric.delta}</p></CardContent></Card>)}</section>
    <section className="grid gap-4 lg:grid-cols-[1.1fr_0.9fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Users className="h-5 w-5 text-primary" />游客经营漏斗</CardTitle></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-5">{workflowColumns.map((column, index) => <button key={column.id} type="button" onClick={onMonitor} className="rounded-lg bg-muted/60 p-3 text-left transition-colors hover:bg-primary/5"><div className="mb-5 flex items-center gap-2 text-xs font-medium text-muted-foreground"><span className={`h-2 w-2 rounded-full ${column.color}`} />0{index + 1}</div><div className="font-semibold">{column.title}</div><div className="mt-1 text-xs text-muted-foreground">{column.description}</div></button>)}</div></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><MessageCircle className="h-5 w-5 text-amber-500" />今日机会</CardTitle></CardHeader><CardContent className="space-y-3"><div className="rounded-lg bg-amber-50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-amber-950">3 位游客等待及时回复</p><p className="mt-1 text-xs text-amber-800/75">川西稻城路线内容带来新咨询</p></div><Mountain className="h-5 w-5 text-amber-600" /></div></div><div className="flex items-center justify-between rounded-lg border p-4"><div><p className="font-medium">今日待处理 · 8 项</p><p className="mt-1 text-xs text-muted-foreground">按优先级已整理</p></div><Button variant="subtle" size="sm" onClick={onMonitor}>去处理</Button></div></CardContent></Card></section>
  </div>;
}
