import { useEffect, useState } from "react";
import { ChevronRight, CircleDollarSign, Target, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { overviewMetrics, type Channel, type Visitor } from "@/data/tourism";

export function OverviewPage({ visitors, onMonitor, onReport }: { visitors: Visitor[]; onMonitor: () => void; onReport?: () => void }) {
  const [period, setPeriod] = useState("today");
  const [channel, setChannel] = useState<Channel>("all");
  const [focusedMetric, setFocusedMetric] = useState<string | null>(null);
  const [opportunitiesOpen, setOpportunitiesOpen] = useState(false);
  const [liveIndex, setLiveIndex] = useState(0);
  const periodLabel = period === "today" ? "今日" : period === "24h" ? "近 24 小时" : period === "7d" ? "近 7 日累计" : "近 30 日累计";
  useEffect(() => { const timer = window.setInterval(() => setLiveIndex((index) => index + 1), 4500); return () => window.clearInterval(timer); }, []);
  const periodFactor = period === "today" ? 1 : period === "24h" ? 1.15 : period === "7d" ? 5.8 : 21.4;
  const dealCount = visitors.filter((visitor) => visitor.stage === "deal").length;
  const liveMetrics = overviewMetrics.map((metric, index) => index === 0 ? { ...metric, value: String(Math.max(1, Math.round(dealCount * periodFactor))) } : index === 1 ? { ...metric, value: Math.round(dealCount * 8600 * periodFactor).toLocaleString() } : { ...metric, value: Math.round(dealCount * 1860 * periodFactor).toLocaleString() });
  const stageCounts = { breakthrough: visitors.filter((visitor) => visitor.stage === "breakthrough").length, intent: visitors.filter((visitor) => visitor.stage === "intent").length, plan: visitors.filter((visitor) => visitor.stage === "plan").length, booking: visitors.filter((visitor) => visitor.stage === "booking").length, deal: visitors.filter((visitor) => visitor.stage === "deal").length };
  const channelCounts = { dy: visitors.filter((visitor) => visitor.channel === "dy").length, xhs: visitors.filter((visitor) => visitor.channel === "xhs").length, wx: visitors.filter((visitor) => visitor.channel === "wx").length };
  return <div className="space-y-3">
    <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex items-center gap-3 border-b bg-slate-50/70 px-4 py-2"><span className="text-sm font-semibold">欢迎回来</span><span className="rounded-full border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-xs text-emerald-600">🌱 新人期</span><span className="text-xs text-muted-foreground">你已连续出勤 <b>12 天</b>，节奏越来越稳 · 今天也要加油！</span></div><div className="grid gap-3 p-3 lg:grid-cols-[1fr_1fr_1fr]">
      <MetricCard metric={liveMetrics[0]} icon={<Target className="h-4 w-4" />} tone="rose" focused={focusedMetric === liveMetrics[0].label} onClick={() => setFocusedMetric(liveMetrics[0].label)} />
      <MetricCard metric={liveMetrics[1]} icon={<TrendingUp className="h-4 w-4" />} tone="sky" focused={focusedMetric === liveMetrics[1].label} onClick={() => setFocusedMetric(liveMetrics[1].label)} />
      <MetricCard metric={liveMetrics[2]} icon={<CircleDollarSign className="h-4 w-4" />} tone="amber" focused={focusedMetric === liveMetrics[2].label} onClick={() => setFocusedMetric(liveMetrics[2].label)} />
    </div></section>
    <div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2"><span className="text-sm font-semibold">游客池</span><span className="rounded-full bg-amber-50 px-2 py-1 text-xs text-amber-700">💧 漏斗思维</span><span className="text-xs text-muted-foreground">咨询×2 · 旅行线索×2 · 游客×2，越往后越值钱，别在顶层漏水</span></div><div className="flex items-center gap-2"><span className="text-xs text-muted-foreground">{periodLabel}</span><Tabs value={period} onValueChange={setPeriod}><TabsList aria-label="经营周期"><TabsTrigger value="today">今日</TabsTrigger><TabsTrigger value="24h">24h</TabsTrigger><TabsTrigger value="7d">7日</TabsTrigger><TabsTrigger value="30d">30日</TabsTrigger></TabsList></Tabs></div></div>
    {focusedMetric && <p role="status" className="text-xs text-primary"><span>{focusedMetric === "今日成交" ? "成交趋势已聚焦" : `${focusedMetric}趋势已聚焦`}</span> · {periodLabel}</p>}
    <section className="grid gap-0 overflow-hidden rounded-xl border bg-white shadow-sm lg:grid-cols-[220px_220px_1fr]"><ChannelPanel counts={channelCounts} channel={channel} onChannelChange={setChannel} /><MiniLeadPanel /><div className="min-w-0 border-t p-3 lg:border-l lg:border-t-0"><div className="flex items-end gap-3"><div><p className="text-sm font-semibold">游客 · 经营 5 阶段</p><p className="mt-1 text-3xl font-bold">{visitors.length}<span className="ml-1 text-sm font-normal text-muted-foreground">人</span></p></div><span className="text-xs text-emerald-600">环比 <b>+6.3%</b></span><span className="text-xs text-emerald-600">转化率 <b>{visitors.length ? ((stageCounts.deal / visitors.length) * 100).toFixed(1) : "0.0"}%</b></span><span className="text-xs text-muted-foreground">今日成交 <b className="text-foreground">{stageCounts.deal} 件</b></span></div><div className="mt-3 grid min-h-[178px] grid-cols-5 gap-1"><FunnelStage index={0} title="首次咨询" value={String(stageCounts.breakthrough)} color="bg-slate-100" onClick={onMonitor} /><FunnelStage index={1} title="需求确认" value={String(stageCounts.intent)} color="bg-slate-100" onClick={onMonitor} /><FunnelStage index={2} title="方案报价" value={String(stageCounts.plan)} color="bg-slate-100" onClick={onMonitor} /><FunnelStage index={3} title="预订支付" value={String(stageCounts.booking)} color="bg-blue-100" onClick={onMonitor} /><FunnelStage index={4} title="出行服务" value={String(stageCounts.deal)} color="bg-blue-600" dark onClick={onMonitor} /></div></div></section>
    <LiveActivityFeed visitors={visitors} index={liveIndex} />
    <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex items-center gap-3 border-b px-4 py-2"><span className="text-sm font-semibold">机会中心</span><span className="rounded-full bg-blue-50 px-2 py-1 text-xs text-blue-600">✨ 今日 3 个机会</span><span className="text-xs text-muted-foreground">AI 已按优先级排好，挑一个开始 · <b>你只负责点击</b></span></div><div className="grid gap-3 p-3 xl:grid-cols-3"><OpportunityCard tone="amber" icon="🔥" title="趁热回复这 3 条高意向咨询" detail="《川西稻城路线攻略》出圈带来 8 条咨询，3 位游客已问“怎么买”" action="去回复" onClick={() => setOpportunitiesOpen(true)} /><OpportunityCard tone="blue" icon="🏆" title="陈导 高客单订单 5 步全拆解" detail="从进线到成交只用 19 天，埋钩子是重点" action="查看拆解" onClick={() => setOpportunitiesOpen(true)} /><OpportunityCard tone="green" icon="✍️" title="给女儿买的第一份亲子游" detail="本周同类点击 5.2%，你的 50+ 女性粉丝占 42%" action="看初稿" onClick={() => setOpportunitiesOpen(true)} /></div>{opportunitiesOpen && <div className="mx-3 mb-3 rounded-lg border border-primary/20 bg-primary/5 p-3 text-sm"><b>待回复 3 条 · 高意向 8 条</b><p className="mt-1 text-xs text-muted-foreground">已为奶爸不躺平、月亮邮差生成分人话术，可以进入游客监控继续处理。</p><Button size="sm" className="mt-2" onClick={onMonitor}>去处理</Button></div>}<Button className="sr-only" aria-label="展开今日机会" onClick={() => setOpportunitiesOpen((value) => !value)}>展开</Button></section>
  </div>;
}

function MetricCard({ metric, icon, tone, focused, onClick }: { metric: typeof overviewMetrics[number]; icon: React.ReactNode; tone: string; focused: boolean; onClick: () => void }) {
  return <button type="button" aria-label={metric.label} onClick={onClick} className="text-left"><Card className={`relative h-full overflow-hidden border-l-4 transition-shadow hover:shadow-md ${tone === "rose" ? "border-l-rose-500" : tone === "sky" ? "border-l-sky-500" : "border-l-amber-500"} ${focused ? "ring-2 ring-primary/30" : ""}`}><CardContent className="p-3"><div className="flex items-center justify-between text-xs text-muted-foreground"><span className="flex items-center gap-2"><span className={`rounded-full p-1.5 ${tone === "rose" ? "bg-rose-100 text-rose-500" : tone === "sky" ? "bg-sky-100 text-sky-500" : "bg-amber-100 text-amber-600"}`}>{icon}</span>{metric.label}</span><span className="rounded-full bg-muted px-2 py-1">{metric.delta}</span></div><div className="mt-1 text-2xl font-bold">{metric.value}<span className="ml-1 text-xs font-normal text-muted-foreground">{metric.unit}</span></div><div className="mt-2 h-1 rounded-full bg-muted"><div className={`h-full rounded-full ${tone === "rose" ? "w-[30%] bg-rose-500" : tone === "sky" ? "w-[82%] bg-sky-500" : "w-[62%] bg-amber-500"}`} /></div><p className="mt-2 text-xs text-muted-foreground">{tone === "rose" ? "🎉 开门红，一鼓作气冲今天第 2 单" : tone === "sky" ? "⚡ 超过 82% 同期新人，节奏很棒" : "🚀 距本月目标还差 1,140 元，加油"}</p></CardContent></Card></button>;
}

function LiveActivityFeed({ visitors, index }: { visitors: Visitor[]; index: number }) {
  const messages = visitors.slice(0, 6).map((visitor, position) => ({
    visitor,
    text: position % 3 === 0 ? `${visitor.name}刚刚更新了咨询状态` : position % 3 === 1 ? `${visitor.name}进入${visitor.status}，建议及时跟进` : `${visitor.subtitle ?? "渠道咨询"}带来新的旅行需求`,
  }));
  const current = messages[index % messages.length];
  return <section className="rounded-xl border bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-2 border-b px-4 py-2"><div className="flex items-center gap-2"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-500" /><span className="text-sm font-semibold">实时动态</span><span className="text-xs text-muted-foreground">游客、渠道和订单消息自动刷新</span></div><span className="text-xs text-muted-foreground">每 4.5 秒更新</span></div><div className="grid gap-2 p-3 md:grid-cols-3">{[0, 1, 2].map((offset) => { const item = messages[(index + offset) % messages.length]; return <div key={`${item.visitor.id}-${offset}`} className={`rounded-lg border p-3 transition-colors ${offset === 0 ? "border-emerald-200 bg-emerald-50/70" : "bg-slate-50/60"}`}><div className="flex items-center justify-between gap-2"><span className="truncate text-sm font-medium">{item.visitor.name}</span><span className="shrink-0 text-[11px] text-muted-foreground">{item.visitor.time ?? "刚刚"}</span></div><p className="mt-1 line-clamp-1 text-xs text-muted-foreground">{item.text}</p><span className="mt-2 inline-flex rounded-full bg-white px-2 py-0.5 text-[11px] text-primary">{item.visitor.channel === "xhs" ? "小红书" : item.visitor.channel === "dy" ? "抖音" : "企业微信"}</span></div>; })}</div><p className="sr-only" role="status">{current.text}</p></section>;
}

function ChannelPanel({ counts, channel, onChannelChange }: { counts: { dy: number; xhs: number; wx: number }; channel: Channel; onChannelChange: (channel: Channel) => void }) {
  const rows = channel === "all" ? [["抖音", counts.dy, "↑ 68%"], ["小红书", counts.xhs, "↑ 40%"], ["企业微信", counts.wx, "↑ 22%"]] : channel === "dy" ? [["抖音", counts.dy, "↑ 68%"]] : channel === "xhs" ? [["小红书", counts.xhs, "↑ 40%"]] : [["企业微信", counts.wx, "↑ 22%"]];
  const total = channel === "all" ? counts.dy + counts.xhs + counts.wx : channel === "dy" ? counts.dy : channel === "xhs" ? counts.xhs : counts.wx;
  return <div className="border-b p-3 lg:border-b-0"><div className="flex items-center justify-between"><p className="text-sm font-semibold">渠道咨询</p><span className="text-xs text-muted-foreground">发帖 3 · 互动 1.4k</span></div><Tabs value={channel} onValueChange={(value) => onChannelChange(value as Channel)} className="mt-2"><TabsList className="h-7 max-w-full overflow-x-auto"><TabsTrigger className="px-2 py-1 text-[11px]" value="all">全部</TabsTrigger><TabsTrigger className="px-2 py-1 text-[11px]" value="xhs">小红书</TabsTrigger><TabsTrigger className="px-2 py-1 text-[11px]" value="dy">抖音</TabsTrigger><TabsTrigger className="px-2 py-1 text-[11px]" value="wx">企业微信</TabsTrigger></TabsList></Tabs><div className="mt-3"><b className="text-2xl">{total}</b><span className="ml-1 text-xs text-muted-foreground">条/日</span><span className="ml-2 text-xs text-emerald-600">↑ 58%</span></div><div className="mt-3 space-y-2">{rows.map(([name, value, change]) => <div className="flex items-center justify-between text-xs" key={name}><span>• {name}</span><span><b>{value}</b> 条 <span className="text-emerald-600">{change}</span></span></div>)}</div></div>;
}

function MiniLeadPanel() { return <div className="border-b p-3 lg:border-b-0 lg:border-l"><div className="flex items-center justify-between"><p className="text-sm font-semibold">旅行线索</p><span className="text-xs text-muted-foreground">B 级</span></div><div className="mt-3"><b className="text-2xl">18</b><span className="ml-1 text-xs text-muted-foreground">条</span><span className="ml-2 text-xs text-emerald-600">↑ 9.8%</span></div><div className="mt-4 space-y-3 text-xs"><div className="flex justify-between"><span>• 抖音留资</span><span><b>11</b> 条 <span className="text-emerald-600">↑ 12%</span></span></div><div className="flex justify-between"><span>• 小红书留资</span><span><b>7</b> 条 <span className="text-emerald-600">↑ 22%</span></span></div></div></div>; }
function FunnelStage({ index, title, value, color, dark, onClick }: { index: number; title: string; value: string; color: string; dark?: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={`flex flex-col justify-end p-2 text-left transition-transform hover:-translate-y-0.5 ${color} ${dark ? "text-white" : "text-slate-500"}`}><span className="text-[11px]">{index + 1} {title}</span><b className="mt-1 text-lg">{value}<small className="ml-1 text-xs font-normal">人</small></b><span className={`text-[11px] ${dark ? "text-blue-100" : "text-slate-400"}`}>{index === 4 ? "首次" : `+${index + 3}%`}</span></button>; }
function OpportunityCard({ tone, icon, title, detail, action, onClick }: { tone: string; icon: string; title: string; detail: string; action: string; onClick: () => void }) { return <Card className={`overflow-hidden border-0 bg-gradient-to-br ${tone === "amber" ? "from-amber-50 to-orange-50" : tone === "blue" ? "from-blue-50 to-indigo-50" : "from-emerald-50 to-green-50"}`}><CardHeader className="p-3 pb-2"><div className="flex items-center justify-between text-xs"><span>{icon} 今日最优先</span><span className="rounded-full bg-white/70 px-2 py-1">19:00 前</span></div><CardTitle className="mt-2 text-base">{title}</CardTitle></CardHeader><CardContent className="p-3 pt-0"><p className="min-h-10 text-xs text-muted-foreground">{detail}</p><div className="mt-3 flex items-center justify-between border-t pt-3"><span className="text-xs text-muted-foreground">AI · 转化助手</span><Button size="sm" variant="outline" onClick={onClick}>{action}<ChevronRight className="h-3 w-3" /></Button></div></CardContent></Card>; }
