import { Eye, EyeOff, Plus, Save, ServerCog, Trash2, X } from 'lucide-react'
import { useState } from 'react'
import type { ModelDefinition, Settings } from '../types'

interface Props { open: boolean; settings: Settings; customModels: ModelDefinition[]; onClose: () => void; onSave: (settings: Settings, models: ModelDefinition[]) => void }

export function SettingsDialog({ open, settings, customModels, onClose, onSave }: Props) {
  const [draft, setDraft] = useState(settings)
  const [models, setModels] = useState(customModels)
  const [showKey, setShowKey] = useState(false)
  const [newModelName, setNewModelName] = useState('')
  if (!open) return null
  const addModel = () => { const name = newModelName.trim(); if (!name) return; setModels([...models, { id: `custom-${Date.now()}`, name, vendor: '自定义', mode: 'image', badges: ['自定义'], supportsReference: true, maxReferences: 4, color: '#d991ff' }]); setNewModelName('') }
  return <div className="modal-layer" role="presentation"><div className="settings-modal" role="dialog" aria-modal="true" aria-label="API 设置"><div className="modal-heading"><div><div className="eyebrow">SYSTEM / CONNECTION</div><h3>API 设置</h3></div><button type="button" className="modal-close" onClick={onClose} aria-label="关闭 API 设置"><X size={17} /></button></div><div className="settings-body"><div className="connection-callout"><ServerCog size={18} /><div><strong>{draft.runMode === 'offline' ? '离线演示模式' : '真实 API 模式'}</strong><p>{draft.runMode === 'offline' ? '无需 API Key，适合快速体验完整任务流程。' : '任务将提交到 APImart 并按统一接口轮询结果。'}</p></div><button type="button" className={`toggle ${draft.runMode === 'api' ? 'active' : ''}`} aria-label="API 模式开关" onClick={() => setDraft({ ...draft, runMode: draft.runMode === 'api' ? 'offline' : 'api' })}><span /></button></div><label className="settings-label">Base URL<input aria-label="Base URL" value={draft.baseUrl} onChange={event => setDraft({ ...draft, baseUrl: event.target.value })} /></label><label className="settings-label">API Key<div className="key-input"><input aria-label="API Key" type={showKey ? 'text' : 'password'} value={draft.apiKey} onChange={event => setDraft({ ...draft, apiKey: event.target.value })} placeholder="sk-…" /><button type="button" aria-label="显示 API Key" onClick={() => setShowKey(!showKey)}>{showKey ? <EyeOff size={15} /> : <Eye size={15} />}</button></div></label><label className="settings-check"><input type="checkbox" checked={draft.autoDownload} onChange={event => setDraft({ ...draft, autoDownload: event.target.checked })} />任务成功后自动下载结果</label><div className="custom-models"><div className="settings-subtitle">自定义模型</div>{models.map(model => <div className="custom-model-row" key={model.id}><span className="model-swatch" style={{ background: model.color }} />{model.name}<small>{model.mode === 'image' ? '生图' : '生视频'}</small><button type="button" aria-label={`删除 ${model.name}`} onClick={() => setModels(models.filter(item => item.id !== model.id))}><Trash2 size={13} /></button></div>)}<div className="add-model-row"><input aria-label="自定义模型名称" placeholder="模型显示名称" value={newModelName} onChange={event => setNewModelName(event.target.value)} /><button type="button" onClick={addModel}><Plus size={14} />添加</button></div></div></div><div className="modal-footer"><button type="button" className="toolbar-button" onClick={onClose}>取消</button><button type="button" className="generate-button small-save" onClick={() => { onSave(draft, models); onClose() }}><Save size={14} />保存设置</button></div></div></div>
}
