import { Bot, ChevronRight, MessageSquare, Send, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";

const conversations = ["奶爸不躺平", "奶茶不加糖", "向日葵姐姐", "云端漫游者"];
export function AdvisorPage() {
  return <div className="space-y-5"><div><p className="text-sm font-medium text-primary">旅行顾问工作台</p><h2 className="mt-1 text-2xl font-bold tracking-tight">1v1 对话工作台</h2><p className="mt-2 text-sm text-muted-foreground">集中处理游客消息、复用话术，并让 AI 副驾辅助每一次跟进。</p></div><div className="grid gap-4 lg:grid-cols-[230px_1fr_280px]"><Card className="h-fit"><CardHeader><CardTitle className="text-sm">待处理会话 <Badge variant="secondary">8</Badge></CardTitle></CardHeader><CardContent className="space-y-1 p-2">{conversations.map((name, index) => <button key={name} className={`flex w-full items-center gap-3 rounded-lg p-3 text-left text-sm ${index === 0 ? "bg-primary/10 text-primary" : "hover:bg-muted"}`}><span className="grid h-8 w-8 place-items-center rounded-full bg-gradient-to-br from-rose-300 to-orange-400 text-xs font-bold text-white">{name.slice(0,1)}</span><span className="min-w-0 flex-1 truncate">{name}</span><ChevronRight className="h-4 w-4" /></button>)}</CardContent></Card><Card className="min-h-[520px]"><CardHeader className="border-b"><div className="flex items-center justify-between"><div><CardTitle>奶爸不躺平</CardTitle><p className="mt-1 text-xs text-muted-foreground">企业微信 · 家庭出行 · 1 分钟前</p></div><Badge>实时</Badge></div></CardHeader><CardContent className="flex h-[420px] flex-col justify-between gap-4 p-5"><div className="space-y-4"><div className="max-w-[80%] rounded-2xl rounded-tl-sm bg-muted p-3 text-sm">预算 1.5 万以内能接受，想带孩子去川西。</div><div className="ml-auto max-w-[80%] rounded-2xl rounded-tr-sm bg-primary p-3 text-sm text-primary-foreground">收到，我先按亲子友好、节奏舒适帮你整理两套路线。</div><div className="rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm"><p className="flex items-center gap-2 font-medium text-primary"><Sparkles className="h-4 w-4" />AI 建议</p><p className="mt-1 text-muted-foreground">先确认出行日期和孩子年龄，再推荐路线。</p></div></div><div className="flex gap-2"><Textarea placeholder="输入本次沟通记录或回复…" /><Button size="icon" aria-label="发送"><Send className="h-4 w-4" /></Button></div></CardContent></Card><Card className="h-fit"><CardHeader><CardTitle className="flex items-center gap-2 text-sm"><Bot className="h-4 w-4 text-primary" />AI 副驾</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p className="text-muted-foreground">本轮仅基于最新游客回复生成建议。</p><div className="rounded-lg bg-muted/50 p-3">消费心理：家庭出行需要确定感与低风险承诺。</div><Button className="w-full" variant="outline"><MessageSquare className="h-4 w-4" />一键采用话术</Button></CardContent></Card></div></div>;
}
