import { useEffect, useState } from "react";
import { CheckCircle2, Send, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import type { Visitor } from "@/data/tourism";
import type { ConversationMessage, TimelineEvent, TourismAction } from "@/lib/tourism-state";

export function ConversationDialog({ visitor, timeline = [], messages = [], onClose, onAdvance, onAction, onSend }: { visitor: Visitor | null; timeline?: TimelineEvent[]; messages?: ConversationMessage[]; onClose: () => void; onAdvance: (visitor: Visitor) => void; onAction?: (action: TourismAction) => void; onSend?: (text: string) => void }) {
  const [draft, setDraft] = useState("");
  const [stepIndex, setStepIndex] = useState(0);
  const scenarioSteps = ["游客消息已接收", "AI 识别旅行需求", "顾问确认出行信息", "推送匹配行程方案", "推进到下一阶段"];
  useEffect(() => setStepIndex(0), [visitor?.id]);
  const send = () => { if (draft.trim()) { onSend?.(draft); setDraft(""); } };
  const runScenarioStep = () => { const next = Math.min(stepIndex + 1, scenarioSteps.length - 1); setStepIndex(next); if (next === 2) onAction?.("qualify"); if (next === scenarioSteps.length - 1) onAdvance(visitor!); };
  return <Dialog open={Boolean(visitor)} onOpenChange={(open) => { if (!open) onClose(); }}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{visitor?.name}</DialogTitle><DialogDescription>{visitor?.subtitle} · 当前状态：{visitor?.status}</DialogDescription></DialogHeader>{visitor && <div className="space-y-4"><div className="rounded-lg bg-muted/60 p-4 text-sm">游客说：<span className="font-medium">“{visitor.lastMessage}”</span></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => onAction?.("retain")}>留资</Button><Button size="sm" variant="outline" onClick={() => onAction?.("wechat")}>加企微</Button><Button size="sm" variant="outline" onClick={() => onAction?.("takeover")}>接管会话</Button><Button size="sm" variant="outline" onClick={() => onAction?.("qualify")}><Sparkles className="h-4 w-4" />确认意向</Button></div><div className="rounded-lg border bg-slate-50/70 p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-medium text-muted-foreground">场景推进 · {stepIndex + 1}/{scenarioSteps.length}</p><Button size="sm" variant="outline" onClick={runScenarioStep}>{stepIndex === scenarioSteps.length - 1 ? "已完成" : "执行下一步"}</Button></div><div className="mt-3 grid gap-2 sm:grid-cols-5">{scenarioSteps.map((step, index) => <div key={step} className={`rounded-md px-2 py-2 text-center text-[11px] ${index <= stepIndex ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}>{index + 1}. {step}</div>)}</div></div><div className="rounded-lg border p-4"><p className="mb-3 text-xs font-medium text-muted-foreground">下一步建议</p><div className="flex items-center gap-2 text-sm"><CheckCircle2 className="h-4 w-4 text-emerald-600" />确认关键信息后推进至下一阶段</div></div><div className="space-y-2 rounded-lg bg-muted/30 p-3 text-sm"><p className="font-medium">沟通记录</p>{messages.filter((message) => message.visitorId === visitor.id).map((message) => <div key={message.id} className={message.sender === "advisor" ? "ml-auto max-w-[80%] rounded-lg bg-primary p-2 text-primary-foreground" : "max-w-[80%] rounded-lg bg-background p-2"}>{message.text}</div>)}{timeline.map((event) => <div key={event.id} className="text-xs text-muted-foreground">{event.time} · {event.label}：{event.detail}</div>)}</div><div className="flex gap-2"><Textarea value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="输入给游客的回复…" /><Button size="icon" aria-label="发送回复" onClick={send} disabled={!draft.trim()}><Send className="h-4 w-4" /></Button></div><div className="flex flex-wrap justify-end gap-2"><Button variant="outline" onClick={onClose}>稍后处理</Button><Button onClick={() => { onAdvance(visitor); onClose(); }}>推进下一阶段</Button></div></div>}</DialogContent></Dialog>;
}
