import { useState } from "react";
import { CheckCircle2, FilePlus2, Image, MoreHorizontal, PenLine } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";

type ContentItem = { title: string; meta: string; status: string };
const initialQueue: ContentItem[] = [{ title: "川西稻城 6 日攻略", meta: "图文攻略 · 小红书", status: "待审核" }, { title: "暑期三亚亲子路线", meta: "短视频脚本 · 抖音", status: "高潜线索" }, { title: "新疆包车避坑指南", meta: "直播切片 · 视频号", status: "编辑中" }, { title: "关西自由行行程模板", meta: "模板复用 · 站内搜索", status: "已发布" }];
export function ContentPage() {
  const [queue, setQueue] = useState(initialQueue);
  const [open, setOpen] = useState(false);
  const [title, setTitle] = useState("");
  const save = () => { if (title.trim()) { setQueue((items) => [{ title: title.trim(), meta: "旅游攻略 · 待配置渠道", status: "草稿" }, ...items]); setTitle(""); setOpen(false); } };
  const publish = (item: ContentItem) => setQueue((items) => items.map((current) => current.title === item.title ? { ...current, status: "已发布" } : current));
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-medium text-primary">TRAVEL OPS · CONTENT STUDIO</p><h2 className="mt-1 text-2xl font-bold tracking-tight">旅游内容中心</h2><p className="mt-2 text-sm text-muted-foreground">把目的地内容变成可持续的咨询和订单。</p></div><Button onClick={() => setOpen(true)}><FilePlus2 className="h-4 w-4" />新建内容</Button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["待审核内容", "12", "较昨日 +3"], ["本周发布", "28", "覆盖 6 个目的地"], ["内容带来咨询", "436", "转化率 8.6%"], ["内容带来 GMV", "¥186,400", "环比 +18.2%"]].map(([label, value, delta]) => <Card key={label}><CardHeader className="pb-2"><CardTitle className="text-xs text-muted-foreground">{label}</CardTitle></CardHeader><CardContent><p className="text-2xl font-bold">{value}</p><p className="mt-2 text-xs text-emerald-600">{delta}</p></CardContent></Card>)}</div><div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><Card><CardHeader><CardTitle>内容生产队列</CardTitle></CardHeader><CardContent className="space-y-1">{queue.map((item) => <div key={item.title} className="flex flex-wrap items-center gap-3 border-b py-4 last:border-0"><div className="grid h-10 w-10 place-items-center rounded-lg bg-muted"><Image className="h-5 w-5 text-muted-foreground" /></div><div className="min-w-0 flex-1"><p className="font-medium">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{item.meta}</p></div><Badge variant="secondary">{item.status}</Badge>{item.status !== "已发布" && <Button size="sm" variant="outline" onClick={() => publish(item)}>发布</Button>}<Button size="icon" variant="ghost" aria-label={`编辑${item.title}`}><PenLine className="h-4 w-4" /></Button></div>)}</CardContent></Card><Card><CardHeader><CardTitle>目的地内容表现</CardTitle></CardHeader><CardContent className="space-y-4">{[["三亚亲子游", "收藏率 12.8% · 咨询 86"], ["川西自驾", "咨询 86 · 订单 14"], ["新疆包车", "成交 GMV ¥42,600"]].map(([destination, meta]) => <div key={destination} className="flex items-center justify-between rounded-lg bg-muted/40 p-3"><div><p className="font-medium">{destination}</p><p className="mt-1 text-xs text-muted-foreground">{meta}</p></div><MoreHorizontal className="h-4 w-4 text-muted-foreground" /></div>)}<p className="flex items-center gap-2 text-xs text-emerald-600"><CheckCircle2 className="h-4 w-4" />内容数据每 30 分钟同步</p></CardContent></Card></div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>新建旅游内容</DialogTitle><DialogDescription>保存后进入内容生产队列。</DialogDescription></DialogHeader><div className="space-y-4"><Textarea aria-label="内容标题" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="输入内容标题…" /><Button className="w-full" onClick={save} disabled={!title.trim()}>保存草稿</Button></div></DialogContent></Dialog></div>;
}
